server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/workflow?characterEncoding=utf-8&useSSL=false
    username: root
    password: ecnuscsse
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL55Dialect

