server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://scsse.cn/Workflow?characterEncoding=utf-8&useSSL=true
    username: root
    password: ecnuscssetia
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    show-sql: true

